package dev.alloy.hooks.testing;

import java.util.ArrayList;
import java.util.List;

/**
 * Event log shared by the fake game and the fake Forge runtime, so a test can read in order
 * everything that happened during a call.
 *
 * <p>Static because generated bytecode can only reach a fixed address.</p>
 */
public final class GameTrace {

    private static final List<String> EVENTS = new ArrayList<>();

    /** Number of {@code true} values {@link #next()} still has to return. */
    private static int pendingInputs;

    private GameTrace() {
    }

    /** Clears the log; call before each test. */
    public static synchronized void reset() {
        GameTrace.EVENTS.clear();
        GameTrace.pendingInputs = 0;
    }

    /** Records an event. */
    public static synchronized void record(String event) {
        GameTrace.EVENTS.add(event);
    }

    /** Returns, in order, a copy of the events recorded since the last {@link #reset()}. */
    public static synchronized List<String> events() {
        return List.copyOf(GameTrace.EVENTS);
    }

    /** Queues fake input events: {@link #next()} will return {@code true} {@code count} times. */
    public static synchronized void queueInputs(int count) {
        GameTrace.pendingInputs = count;
    }

    /** Stands in for {@code Mouse.next()}: tells whether an input event is left to process. */
    public static synchronized boolean next() {
        GameTrace.EVENTS.add("next");
        if (GameTrace.pendingInputs > 0) {
            GameTrace.pendingInputs--;
            return true;
        }
        return false;
    }
}
